version: '3.8'

services:
  bot:
    build: .
    container_name: smartplagas-bot
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - backend

  backend:
    build: ./smartplagas-backend
    container_name: smartplagas-backend
    ports:
      - "3001:3001"
    env_file:
      - ./smartplagas-backend/.env
